server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=car_management;encrypt=true;trustServerCertificate=true
    username: springuser
    password: admin123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: your_super_secret_key_which_should_be_very_long
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html